#ifndef GLOBALS_H
#define GLOBALS_H

#define CHIP8_DISPLAY_FPS 60
#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32

#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_MEMORY_BEGIN 0x200
#define CHIP8_TIMERS_TICKS_PER_SECOND 60
#define CHIP8_STACK_SIZE 16

#endif // GLOBALS_H